apiVersion: skaffold/v3
kind: Config

build:

  tagPolicy:
    envTemplate:
      template: "{{.BUILD_ID}}"

  artifacts:
  - image: asia.gcr.io/advancedware/serverless-workflow-backend
    context: .
    docker:
      dockerfile: ./gunicorn/Dockerfile
      cacheFrom:
      # googleCloudBuild replaces cache references to the artifact image with
      # the tagged image reference, useful for caching from the previous build.
      - asia.gcr.io/advancedware/serverless-workflow-backend:latest
  googleCloudBuild:
    projectId: "advancedware"
