# Generated by Django 3.1.7 on 2021-07-03 12:21

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('task_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Completed'), (2, 'Errors')], default=0)),
                ('sub_task_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Completed'), (2, 'Errors')], default=0)),
                ('code', models.TextField()),
                ('request', models.JSONField(null=True)),
                ('response', models.JSONField(null=True)),
                ('immediate_next', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(null=True), null=True, size=None)),
                ('sub_task_next', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(null=True), null=True, size=None)),
                ('parent_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_task', to='task_services.task')),
            ],
        ),
    ]
