# Generated by Django 3.2.10 on 2022-03-03 12:28

from uuid import uuid4
from django.db import migrations

def update_task_ids(apps, schema_editor):

    task_model  = apps.get_model('task_services','Task')

    task_model.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('task_services', '0003_auto_20220209_0634'),
    ]

    operations = [
        migrations.RunPython(update_task_ids, reverse_code=migrations.RunPython.noop),
    ]
