# Generated by Django 3.2.10 on 2022-03-03 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_services', '0004_auto_20220303_1228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
