# Generated by Django 3.2.10 on 2022-03-03 13:39

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('task_services', '0005_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Completed'), (2, 'Errors')], default=0)),
                ('sub_task_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Completed'), (2, 'Errors')], default=0)),
                ('code', models.TextField()),
                ('request', models.JSONField(null=True)),
                ('response', models.JSONField(null=True)),
                ('immediate_next', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(null=True), null=True, size=None)),
                ('sub_task_next', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(null=True), null=True, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('my_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('parent_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_task', to='task_services.task')),
            ],
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('my_user', 'code'), name='Unique_User-Code'),
        ),
    ]
