# Generated by Django 4.0.4 on 2022-04-23 09:07

from django.db import migrations, models
import django.db.models.expressions
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('task_services', '0006_auto_20220303_1339'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='Unique_User-Code',
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(django.db.models.expressions.F('my_user'), django.db.models.functions.text.MD5('code'), name='Unique_User-Code'),
        ),
    ]
